### ISSUE TITLE
Feature request: Support pastebin sites

### ISSUE THREAD

**Issue by deletescape** [postlight/mercury-parser#262]
- **Platform**:
- **Mercury Parser Version**:
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**:

## Steps to Reproduce

Pastebin sites like e.g. hastebin.com, del.dog or pastebin.com currently produce pretty broken results.

Examples:
https://hastebin.com/about.md
![image](https://user-images.githubusercontent.com/13785669/52479195-19de2600-2ba8-11e9-8b9b-d7d4299f5f90.png)
https://del.dog/about.md
![image](https://user-images.githubusercontent.com/13785669/52479232-3a0de500-2ba8-11e9-927d-5bcca193a223.png)
https://pastebin.com/pipKY6pX
![image](https://user-images.githubusercontent.com/13785669/52479243-46923d80-2ba8-11e9-9c37-f22c26a2d61f.png)

## Detailed Description

I am the creator of dogbin and would obviously love if it would beautifully show up here. This does however seem to generally apply to formatted code blocks and pastebin.com seems to be broken in other ways as well.

**Comment by adampash** [comment]
@deletescape Is the problem you're reporting with the parser, or with the way parsed results are rendered in Mercury Reader? From your screenshots, I suspect it may be a little of both.

Re: better supporting the _parsing_ of any of the sites (which is the purview of Mercury Parser), we welcome pull requests for custom parsers — and [they're accessible to most developers](https://github.com/postlight/mercury-parser/blob/master/src/extractors/custom/README.md).

Where it may be a Mercury Reader issue, that's tougher. It looks to me like most of these sites use `code` and/or `pre` blocks to render the text, and Mercury Reader has some specific styling decisions around those kinds of element, optimizing for code blocks in larger portions of HTML, which isn't necessarily optimized for pastebin sites, but is well optimized for most of the rest of the web.
