### ISSUE TITLE
Russian Webpage parsing support.

### ISSUE THREAD

**Issue by mrgodhani** [postlight/mercury-parser#263]
- **Platform**: Mac
- **Mercury Parser Version**: Web based api (at moment)
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**:

## Expected Behavior

Proper encoding for Russian language.

## Current Behavior
When parsing this link https://www.finam.ru/analysis/newsitem/putin-nagradil-grefa-ordenom-20190208-203615/?utm_source=rss&utm_medium=new_compaigns&utm_campaign=news_to_finamb it doesn't give proper encode output and hence format is messed up when rendering in html.

## Steps to Reproduce

1. Parse link https://www.finam.ru/analysis/newsitem/putin-nagradil-grefa-ordenom-20190208-203615/?utm_source=rss&utm_medium=new_compaigns&utm_campaign=news_to_finamb
2.  Check the content output
3. Try to render that content with Cyrillic font 
4. You will see instead of proper format it shows bunch of '�'

## Detailed Description

I use this API for parsing articles in my reader app. And there are some Russian news feed try to use and are not able to get proper format output.

**Comment by mrgodhani** [comment]
More reference https://github.com/mrgodhani/raven-reader/issues/269

**Comment by HenryQW** [comment]
The same applies to Chinese and other Asian languages, you get a bunch of unicodes rather than the actual content.

**Comment by adampash** [comment]
Thanks for reporting @mrgodhani — and @HenryQW. I'll be honest: I don't have a ton of experience with encoding in these scenarios. This is where the encoding currently takes place:

https://github.com/postlight/mercury-parser/blob/master/src/resource/index.js#L63-L79

Does anything stand out to you as _doing it wrong_? Or any other suggestions? We're more than happy to accept help.

**Comment by vjyanand** [comment]
My findings 
1) Change regex case-insensitive 

`var ENCODING_RE = /charset=([\w-]+)\b/I;`

2) Check truthfulness of metaContentType before comparing 

`if (metaContentType && properEncoding !== encoding) {`

Thanks

**Comment by mrgodhani** [comment]
@adampash  I tested @vjyanand's fix and that's working well.

**Comment by toufic-m** [comment]
This fix has been merged, and will be included in the next release.

**Comment by MindfulMe** [comment]
Did you get it released? I have the following when parsing Russian language articles 
<img width="1680" alt="Screenshot 2020-08-03 at 02 19 06" src="https://user-images.githubusercontent.com/26275425/89134697-b5e3b600-d52f-11ea-9e5d-d195198e8545.png">
