### ISSUE TITLE
Using a prepared response buffer always throws "No children, likely a bad parse."

### ISSUE THREAD

**Issue by miickel** [postlight/mercury-parser#265]
- **Platform**: Darwin mickel 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
- **Mercury Parser Version**: 1.1.1
- **Node Version (if a Node bug)**: 8.12.0

## Expected Behavior

When using `Mercury.parse` with a prepared html response, I expect it to be able to parse it.

## Current Behavior

Throws error "No children, likely a bad parse."

## Steps to Reproduce

``` javascript
const html = Buffer.from(`<html><head><meta charset="utf-8"></head><body><p id="PXeWGg">This is a test</p> <p id="NSYfDg">Hello!.</p></body></html>`, 'utf8')
const result = await Mercury.parse('https://example.com/page', { html }) // throws error
```

**Comment by adampash** [comment]
@miickel Apologies for the confusion. I'm in the process of updating the signature of the `parse` function. The previous signature, and the one that's int he version of Mercury you're using, looks like this:

`Mercury.parse(url, html)` (notice `html` isn't part of an object).

Hope that helps!
