### ISSUE TITLE
Pass custom headers to Request

### ISSUE THREAD

**Issue by vjyanand** [postlight/mercury-parser#268]
Need option to pass custom headers to Request. Thanks

**Comment by adampash** [comment]
I'm in support of this feature. @vjyanand is this something you'd be interested in submitting a PR for?

**Comment by vjyanand** [comment]
Not sure of where to pass custom headers from. Probably as part of custom extractors ?

**Comment by vjyanand** [comment]
Also, ability to add custom parsers adhoc

**Comment by toufic-m** [comment]
@vjyanand A good place to start from for passing custom headers would be [`src/resource/utils/fetch-resource.js`](https://github.com/postlight/mercury-parser/blob/master/src/resource/utils/fetch-resource.js#L90). You will notice that we are already passing a `User-Agent` header if the package isn't being used in a browser.

As for the "ability to add custom parsers adhoc", did you mean without having to add code for custom extractors?

**Comment by toufic-m** [comment]
This has been been implemented in #337 and merged into master.
