### ISSUE TITLE
Empty content is returned when parsing `https://www.ncbi.nlm.nih.gov/pubmed/28978556?dopt=Abstract`

### ISSUE THREAD

**Issue by david0leong** [postlight/mercury-parser#281]
- **Platform**: Mac
- **Mercury Parser Version**: 2.00

Empty content is returned when parsing `https://www.ncbi.nlm.nih.gov/pubmed/28978556`

## Current Behavior

When I run `mercury-parser` cli as following:
$ mercury-parser https://www.ncbi.nlm.nih.gov/pubmed/28978556

This is what I receive:

```
{
  "title": "Genomic Heterogeneity as a Barrier to Precision Medicine in Gastroesophageal Adenocarcinoma. - PubMed - NCBI",
  "author": null,
  "date_published": null,
  "dek": null,
  "lead_image_url": null,
  "content": "<div class=\"grid\"> </div>",
  "next_page_url": null,
  "url": "https://www.ncbi.nlm.nih.gov/pubmed/28978556",
  "domain": "www.ncbi.nlm.nih.gov",
  "excerpt": "",
  "word_count": 1,
  "direction": "ltr",
  "total_pages": 1,
  "rendered_pages": 1
}
```

**Comment by adampash** [comment]
@david0leong The easiest solution would be to write a custom parser for this site. [Here's how that works](https://github.com/postlight/mercury-parser/blob/master/src/extractors/custom/README.md). Is that something you'd be interested in doing?
