### ISSUE TITLE
bash: mercury-parser: command not found

### ISSUE THREAD

**Issue by altblog** [postlight/mercury-parser#286]
Platform: Linux s2e24de3f 2.6.32-042stab134.3 #1 SMP Sun Oct 14 12:26:01 MSK 2018 x86_64 GNU/Linux
Node Version: v10.15.1

I installed yarn and npm 10 versions, then executed the command:
```
yarn global add @ postlight / mercury-parser
root @ s2e24de3f: ~ / mercury-parser # yarn global add @ postlight / mercury-parser
yarn global v1.13.0
[1/4] Resolving packages ...
[2/4] Fetching packages ...
[3/4] Linking dependencies ...
[4/4] Building fresh packages ...
success Installed "@ postlight / mercury-parser @ 2.0.0" with binaries:
       - mercury-parser
Done in 2.62s.
```
And then:
```
mercury-parser https://postlight.com/trackchanges/mercury-goes-open-source
The message appears:
-bash: mercury-parser: command not found
```

**Comment by adampash** [comment]
@altblog My best guess is that you haven't added `yarn` binaries to your path. You might want to [check here](https://stackoverflow.com/questions/40317578/yarn-global-command-not-working) for a starting place for how to fix that.
