### ISSUE TITLE
Provide standalone parser package

### ISSUE THREAD

**Issue by zakius** [postlight/mercury-parser#288]
I believe downloading document is out of scope for a parser package and in most cases there are already some downloading solutions existing in project that may vary widely, pulling addition dependencies that won't be used directly by the project seems redundant.

In my opinion providing standalone parser would greatly reduce complexity of the package, reduce reliance on external packages and allow easy inclusion in lightweight projects.

**Comment by adampash** [comment]
This is an interesting thought. In the short term, however, you can pass html directly into Mercury to avoid downloading the html when you already have it on hand:

`Mercury.parse(url, { html })`

**Comment by zakius** [comment]
while it helps slightly it doesn't solve the core issue: huge dependency chain (I meant to add another issue about that but forgot, there is no need for jQuery anymore for example as modern environments are much more consistent) that is especially hard to maintain for frontend solutions

though later I realized that part of the parser has to load additional data to concatenate multiple pages, but I believe this can also be done reliably without such a dependency chain (I looked into it a bit and the best bet would be probably fetch as it works natively in all modern-ish browsers and has almost drop in package for Node)

But I understand that this is a huge scale project that can not be finished in a short time with limited resources but can be a long term goal to consider for future major version
