### ISSUE TITLE
Firefox Port

### ISSUE THREAD

**Issue by yoasif** [postlight/mercury-parser#289]
- **Platform**:
- **Mercury Parser Version**:
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**:

## Expected Behavior
mercury reader appears, I can install. 

## Current Behavior
mercury reader is not found.

## Steps to Reproduce

1. Go to http://addons.mozilla.org/
2. Search for mercury reader

**Comment by adampash** [comment]
@yoasif Mercury Parser is not the same thing as Mercury Reader, though Mercury Reader is powered by the parser.

**Comment by serovar** [comment]
@adampash If not here, where can one request a Mercury Reader port for Firefox (that would be very trivial to do considering the kind of extension), or even a bookmarklet? The same Mercury Reader addon page links to this Github repo, and there are not other way to give this kind of feedback that I can think of.
