### ISSUE TITLE
Bug: Whitespaces like CRLF are removed within <pre> tags

### ISSUE THREAD

**Issue by usr42** [postlight/mercury-parser#310]
- **Platform**:
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Dec 20 21:53:35 PST 2018; root:xnu-3789.73.31~1/RELEASE_X86_64 x86_64
- **Mercury Parser Version**:
2.0.0
- **Node Version (if a Node bug)**:
v11.10.1

## Expected Behavior

When parsing a website containing a `<pre>` tag, whitespaces within the tag should not be changed. If there are new lines/CRLF, tabs or multiple spaces, these characters should remain unchanged.

## Current Behavior

When parsing a website containing a `<pre>` tag, the whitespaces within the tag are removed,  in particular newlines and tabs. This is breaking the contract of a `pre` tag and breaks e.g. code listings on websites.

## Steps to Reproduce

Parse `https://usr42.github.io/mercury-parser-pre-tag/` with following html code:
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page With pre tag</title>
    </head>
    <body>
        <p>Here comes the code:</p>
        <pre>
#!/bin/sh

cd $(dirname "$0") && pwd
        </pre>
    </body>
</html>
```

Run:
```bash
mercury-parser https://usr42.github.io/mercury-parser-pre-tag/
```
Output (abridged):
```json
{
  "content": "<body> <p>Here comes the code:</p> <pre>\n#!/bin/sh cd $(dirname &quot;$0&quot;) &amp;&amp; pwd </pre> </body>",
}
```

Expected output (abridged):
```json
{
  "content": "<body> <p>Here comes the code:</p> <pre>\n#!/bin/sh\n\ncd $(dirname &quot;$0&quot;) &amp;&amp; pwd\n        </pre> </body>",
}
```

## Possible Solution

This issue seems to be related to the usage of `normalizeSpaces()` in [src/extractors/generic/content/extractor.js:83](https://github.com/postlight/mercury-parser/blob/master/src/extractors/generic/content/extractor.js#L83).
Here is a possible diff:
```
diff --git a/src/extractors/generic/content/extractor.js b/src/extractors/generic/content/extractor.js
index b4e57a7..05e6599 100644
--- a/src/extractors/generic/content/extractor.js
+++ b/src/extractors/generic/content/extractor.js
@@ -2,7 +2,6 @@ import cheerio from 'cheerio';

 import { nodeIsSufficient } from 'utils/dom';
 import { cleanContent } from 'cleaners';
-import { normalizeSpaces } from 'utils/text';

 import extractBestNode from './extract-best-node';

@@ -80,7 +79,7 @@ const GenericContentExtractor = {
       return null;
     }

-    return normalizeSpaces($.html(node));
+    return $.html(node);
   },
 };

```
After changing this line, the pre content is fine, but also other whitespaces are not removed.
The parser then generates following output (abridged):
```json
{
  "content": "<body>\n        <p>Here comes the code:</p>\n        <pre>\n#!/bin/sh\n\ncd $(dirname &quot;$0&quot;) &amp;&amp; pwd\n        </pre>\n    </body>",
}
```

Thanks and best regards,
Balthasar aka usr42

**Comment by toufic-m** [comment]
The fix for this issue has been merged into master and will be included in the next release.
