### ISSUE TITLE
How do you run it on AWS Lambda?

### ISSUE THREAD

**Issue by j0k3r** [postlight/mercury-parser#311]
As far as I can see you seems to use AWS Lambda to run the parser.
But I can't see any handlers, serverless or SAM conf.

So, how do you deploy it to AWS? Are you using some extra configuration, like an other repository which encapsulate this one?

**Comment by toufic-m** [comment]
To deploy on AWS, please use the  [Mercury Parser API](https://github.com/postlight/mercury-parser-api) repo, and follow the steps in the README file to install and deploy.
