### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by philclaffey** [postlight/mercury-parser#321]
Hello, 

I am a regular on Windows 10, it simply stopped working...

Any ideas on how to fix it?

Thanks, 

Phil.

**Comment by toufic-m** [comment]
Hello @philclaffey , could you please provide some details about how you were using Mercury Parser and the error(s) you are now receiving?

**Comment by philclaffey** [comment]
Hello,

I am using the extension, I click the button, nothing happens.

Thank you,

Phil.

**Comment by toufic-m** [comment]
Could you please share of some URLs that you are attempting to parse?

Also, if you try to use the extension on other pages, such as: https://postlight.com/trackchanges/mercury-goes-open-source and https://github.com/postlight/mercury-parser , is it also not working?

**Comment by philclaffey** [comment]
Hey,
Strangely enough, it works there, and now elsewhere too!
I discovered that the FaceBook Purity extension - now removed - was
stopping it from functioning.
Thank you so much for your replies and, of course, for this most useful
extension.
Have a fabulous day,
Phil.
