### ISSUE TITLE
Quick start guide? I was using the online API - now its gone I need to set it up on my own server... how?

### ISSUE THREAD

**Issue by pperrin** [postlight/mercury-parser#322]
I was using your service from a script I have running on a dreamhost server. Now the service is discontinued, I need to find an alternative site, or set my own up...

What is the simplest way of doing this? -- ideally once installed I'll just change my scripts to point back at the same server instead of your service.

**Comment by mahboubii** [comment]
@pperrin if your app is on Node you can easily install the parser as dependency, if not you can run it as a standalone service using Express or something similar

**Comment by pperrin** [comment]
@mahboubii thanks for the reply, but the PHP I wrote (5?) years ago is as follows...

`	$resp = @file_get_contents('http://mercury.postlight.com/parser?url=' . urlencode($url), false, $context);
`
I just want the simplest typing exercise to replace this - without having to get into any new tech :).

**Comment by mahboubii** [comment]
@pperrin unfortunately this is JS package and you can't use it directly in php, you have to run another service.

**Comment by pperrin** [comment]
@mahboubii - another service, cool - so how do I do that... I have a dreamhost server I have command line access (but not superuser) what do I need to do to have mercury running as a service?

**Comment by mahboubii** [comment]
@pperrin cheapest and fastest option is using [AWS Lambda](https://aws.amazon.com/lambda/) functions. It's free up to 1M requests/month.

I created a lambda func to setup mercury-parser similar to its old service:
https://github.com/mahboubii/serverless-mercury-parser
