### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mursalal** [postlight/mercury-parser#323]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@2.1.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mitrandir/.npm/_logs/2019-03-12T09_10_45_527Z-debug.log

I am trying install this module. Please help.

**Comment by toufic-m** [comment]
@mursalal could you please provide us with the following information about your development environment?
- **Platform**
- **Node Version**

Also, could you please try manually installing PhantomJS using:
```bash
npm install phantomjs-prebuilt
```
before running:
```bash
yarn install
```

**Comment by mursalal** [comment]
@toufic-m
Platform: Ubuntu 16.04 LTS
Nodejs version: v10.15.3
This is screenshot after `npm install phantomjs-prebuilt`

![Снимок экрана от 2019-03-12 19-27-41](https://user-images.githubusercontent.com/7039741/54217620-0a326400-44fd-11e9-8e1a-f1d39f7b2fe3.png)

This is after running `node test.js`

![Снимок экрана от 2019-03-12 19-30-13](https://user-images.githubusercontent.com/7039741/54217958-a492a780-44fd-11e9-9aa5-9ee38b0964fb.png)

There is test.js:

import Mercury from '@postlight/mercury-parser';
Mercury.parse(url).then(result => console.log(result));

**Comment by toufic-m** [comment]
@mursalal Node.js doesn't support ECMAScript 2015 (ES6)'s `import` syntax by default yet.

You need to use a transpiler, like Babel, in order to transpile your ES6 code to ES5 syntax that Node.js natively supports (check https://github.com/babel/example-node-server for an example Node server with Babel), or you can substitute the `import` statement with a `require(...)` as follows:
```js
const Mercury = require('@postlight/mercury-parser');
```

**Comment by mursalal** [comment]
@toufic-m 
`const Mercury = require('@postlight/mercury-parser');`
It solved my problem. Thank you very much!
