### ISSUE TITLE
Feature Request: paywall authentication

### ISSUE THREAD

**Issue by jspohr** [postlight/mercury-parser#327]
I'm not even sure Mercury Reader is the right place to add this feature, so I apologize in advance if this request is unreasonable.

If would like to see support for reading content from subscription-based websites, which have paywalls before their content. Obviously, this already works if I use Mercury Reader in a browser, and I manually log-in to the paywalled site.
However, when using Mercury indirectly via reading apps like Feedbin, I'm only seeing partial content, or nothing at all.
Pocket provides such a feature: https://help.getpocket.com/article/1065-saving-from-subscription-based-sites
It would be amazing if this could be supported by other reading apps like Reeder, Instapaper, etc.
I'm pretty sure this is not at all easy to implement, and comes with a lot of issues like password storage and other security implications. I have zero background in web technology, so I can't image how difficult this would be to implement, but I imagine it would need a lot of custom solutions for different websites.
I just want to kindly ask for feedback here. Do you think the increasing amount of paywalled content on the internet could be accessed in the nice, clean way that Mercury is able to provide for unrestricted websites?
Or is this something that services like Feedbin would have to provide, with Mercury acting as the back-end?

**Comment by toufic-m** [comment]
I'm currently working on adding the ability to pass custom headers to requests, and depending on the website's implementation for authentication, you might be able to access the full "paywalled" content by passing the right authentication headers.

While this would work for individuals using Mercury Parser directly, the actual authentication (or specifying the authentication headers) through apps that are using Mercury Parser (such as Feedbin), would have to be requested/added on each app individually.

**Comment by jspohr** [comment]
Thanks for the info. I shall contact Feedbin about it, then :)
