### ISSUE TITLE
Cannot parse a javascript-rendered page

### ISSUE THREAD

**Issue by Joshfindit** [postlight/mercury-parser#329]
- **Platform**: `Linux 66784da07322 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux` (node-alpine docker image)
- **Mercury Parser Version**: `@postlight/mercury-parser@^2.0.0`
- **Node Version (if a Node bug)**: `v10.15.3`

## Expected Behavior

Content should be parsed

## Current Behavior

Content is returned blank

```javascript
{ title:
   'News Feature: Deadly deficiency at the heart of an environmental mystery',
  author: null,
  date_published: '2018-10-16T00:00:00.000Z',
  dek: null,
  lead_image_url:
   'https://www.pnas.org/sites/default/files/highwire/pnas/115/42.cover-source.jpg',
  content: '',
  next_page_url: null,
  url: 'https://www.pnas.org/content/115/42/10532',
  domain: 'www.pnas.org',
  excerpt:
   'Researchers are puzzling over a widespread vitamin B shortage that appears to be killing wildlife . During spring and summer, busy colonies of a duck called the common eider ( Somateria mollissima )&hellip;',
  word_count: 1,
  direction: 'ltr',
  total_pages: 1,
  rendered_pages: 1 }
```

## Steps to Reproduce

Attempt to parse https://www.pnas.org/content/115/42/10532

## Possible Solution

Honestly not sure if there is one besides rendering the page in phantom (or similar), and pulling from that

**Comment by toufic-m** [comment]
We’ve considered this, but we will not support this any time soon. It creates far too much overhead to render the page in a headless browser, and most content sites render their content server side for speed and SEO.

Alternatively, users could load such pages in a headless browser on their own, then pass the html into Mercury like `Mercury.parse(url, { html })`
