### ISSUE TITLE
content seemingly parsed - render of parsed content broken

### ISSUE THREAD

**Issue by jmbox80** [postlight/mercury-parser#331]
- **Platform**: Windows 10, 64-bit
- **Mercury Parser Version**: whatever the Mercury Reader Chrome plug-in is using today
- **Node Version (if a Node bug)**: n/a
- **Browser Version (if a browser bug)**: Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)

- **Stack from Chrome dev tools**
redesign
tinypass.min.js:1 TP: Invalid containerSelector
(unknown) ANB
(unknown) --[executed]--> MPS Head Additions (1)
(unknown) --[executed]--> MPS Header Additions (2)
(unknown) Bento Feed Desktop & Tablet
2
pubads_impl_319.js:1 updateCorrelator has been deprecated. Please see the Google Ad Manager help page on "Pageviews in GPT" for more information: https://support.google.com/admanager/answer/183281?hl=en
loader.js:405 Error while loading taboola feed: Cannot read property 'placement' of undefined
impl.350-59-RELEASE.js:3 Exit TRCRBox.loadScriptCallback(retry=0): no items in response - thumbnails-i
2
loader.js:405 Error while loading taboola feed: Cannot read property 'placement' of undefined
(unknown) --[executed]--> MPS Footer Additions (3)
VM235:39 >>> Sailthru tracked with URL PAGE 
VM237:3 Vilynx Recommendation plugin loaded
tinypass.min.js:1 TP: Invalid containerSelector
(unknown) ANB
/.well-known/pubvendors.json:1 Failed to load resource: the server responded with a status of 404 ()
tinypass.min.js:1 TP: Invalid containerSelector
(unknown) [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
0.hola/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
(unknown) ###
socialize.js?apikey=…dQ7gYFCESWKMM1sP:24 proxy request timeout
VM108:17 Uncaught TypeError: Cannot read property 'dataset' of null
    at Object.mps.refreshDetect (<anonymous>:17:33)
    at Object.mps.refreshAds (<anonymous>:181:22)
    at Object.mps.responsiveApply (<anonymous>:105:11)
    at main-31bb0c2….js:12
    at Object.refreshValue (main-31bb0c2….js:12)
    at main-31bb0c2….js:12
    at main-31bb0c2….js:12
    at Array.forEach (<anonymous>)
    at Object.trigger (main-31bb0c2….js:12)
    at main-31bb0c2….js:12

- **Original URL**: [https://www.cnbc.com/2019/03/18/heres-how-cybersecurity-vendors-drive-the-hacking-news-cycle.html](url)

## Expected Behavior

Parsed content should be displayable

## Current Behavior

![image](https://user-images.githubusercontent.com/34203068/54552836-5bbc7200-4987-11e9-99ee-5b5700466d96.png)

I can see what looks like transformed content in the resulting page source after Mercury Reader is applied.  This content is not being rendered in a way that's displayable.

## Steps to Reproduce

Install the Mercury Reader plug-in in Chrome
Visit this article: [https://www.cnbc.com/2019/03/18/heres-how-cybersecurity-vendors-drive-the-hacking-news-cycle.html](url)
Open the article in Mercury Reader

## Detailed Description

[https://www.cnbc.com/2019/03/18/heres-how-cybersecurity-vendors-drive-the-hacking-news-cycle.html](url)

**Comment by toufic-m** [comment]
I am unable to reproduce this, and the full content is displayed for me using the Mercury Reader extension. Is this a persistent issue for you on both this page and other ones?

![Annotation 2019-03-19 104810](https://user-images.githubusercontent.com/13136721/54592237-a2b47100-4a34-11e9-80c8-6279f1a29849.jpg)

I also got the errors in the console, but these are actually from the web site itself, and I'm seeing them before launching the Mercury Reader view.

**Comment by jmbox80** [comment]
For this particular URL it's quite consistent even after browser restart.

Historically, it happens to me occasionally, and randomly as far as I can
tell, that rendering doesn't work. I haven't noticed a particular pattern.
But when this issue does start happening for a page it continues to happen.

Is there anything else I should collect? I can provide you the page source
of the page that is not rendering on the screen. Let me know if you want
that and anything else.

**Comment by jmbox80** [comment]
[bad_render.html.gz](https://github.com/postlight/mercury-parser/files/2983758/bad_render.html.gz)

**Comment by toufic-m** [comment]
I was just able to reproduce this! It seems that CNBC are A/B testing a redesign, and I was always getting the current/standard version, whereas you were getting the new/redesigned version (as seen by the first entry in your console logs: `redesign`).

The redesign changes the HTML structure of article pages, which breaks the existing custom extractor, so I created #336 to address that.

Standard:
![Screenshot_2019-03-21 Desperate to get through to execs, some cybersecurity vendors are resorting to lies and blackmail](https://user-images.githubusercontent.com/13136721/54751991-375dd100-4be5-11e9-9f39-2cf86e0cfb6a.png)

Redesign:
![www cnbc com_2019_03_18_heres-how-cybersecurity-vendors-drive-the-hacking-news-cycle html](https://user-images.githubusercontent.com/13136721/54752001-3dec4880-4be5-11e9-9403-a4643b78a8f1.png)

**Comment by jmbox80** [comment]
Excellent!  Thanks for your perseverance Toufic!
