### ISSUE TITLE
Can't launch a parser

### ISSUE THREAD

**Issue by DanielPtk** [postlight/mercury-parser#332]
Platform: MacOS HeighSierra 10.13.6
Mercury-Parser Version: "@postlight/mercury-parser": "^2.0.0"
Node Version: v11.11.0

Hello.

I have some problems to start  a script in browser. When it starts, console shows:
`Unexpected identifier Mercury. import call expects exactly one argument.`.

Is this Yarn problem or maybe I have to fix some parts of a code?

**Comment by toufic-m** [comment]
Could you please share some code of how you're importing and using the Mercury package in your application?

**Comment by DanielPtk** [comment]
Code of package.json file:
`{
  "name": "mercury-test",
  "version": "1.0.0",
  "main": "index.js",
  "author": "URSA",
  "license": "MIT",
  "dependencies": {
    "@postlight/mercury-parser": "^2.0.0",
    "react": "^16.8.4"
  },
  "scripts": {
    "index": "node index.js"
  }
}`

Next file is just a index.html:

`<script src="index.js"></script>`.

And then index.js with:

`import Mercury from '@postlight/mercury-parser';

Mercury.parse().then(result => console.log(result));`

Mercury parser lib is in "node_modules".

I think that I use JS import incorrectly.

**Comment by mursalal** [comment]
@DanielPtk try this https://github.com/postlight/mercury-parser/issues/323#issuecomment-472350267

**Comment by DanielPtk** [comment]
Better, but now I have `Can't find variable: require` in console. Have I to install some additional modules for this operation?

**Comment by adampash** [comment]
@DanielPtk Are you successfully require-ing/importing any other dependencies? I haven't had any problems importing in the browser, so I'm inclined to think it's likely an environment/config issue. But let us know what you find out.

**Comment by DanielPtk** [comment]
I can't start `require` any lib from my dependencies. Every time I have `Error: Module name "requirejs" has not been loaded yet for context: _. Use require([])`.

I use `require('requirejs');`.
