### ISSUE TITLE
install instructions do not work

### ISSUE THREAD

**Issue by heyalexchoi** [postlight/mercury-parser#338]
first off, big fan of the api - i've been using it for a side project for awhile. disappointed that the web api is breaking down / being taken down, but i suppose it must just be a big money sink.

second, js is not the world i usually live in, so i'm probably doing something wrong. maybe you can help me out. 

- **Platform**: Darwin WOOFWOOFMBP2016.fios-router.home 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
- **Mercury Parser Version**: version "2.0.0"
- **Node Version (if a Node bug)**: v11.11.0
- **Browser Version (if a browser bug)**:

## Expected Behavior
Follow install instructions to run usage example

## Current Behavior
unable to run code in example.
unable to build project via yarn and webpack.

there is no mention of a build step needed, but also i've been seeing reports that suggest building is needed to run the es6 in the example. so maybe a build step *is* needed?

i'm trying to build in webpack after installing via yarn (`yarn add @postlight/mercury-parser`). i am getting errors where webpack cannot resolve the dependencies `cheerio` and `iconv-lite` referenced in `dist/mercury.js`

```
ERROR in ./node_modules/@postlight/mercury-parser/dist/mercury.js
Module not found: Error: Can't resolve 'cheerio' in '/Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/dist'
resolve 'cheerio' in '/Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/dist'
  Parsed request is a module
  using description file: /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/package.json (relative path: ./dist)
    aliased from description file /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/package.json with mapping 'cheerio' to './src/shims/cheerio-query'
      using description file: /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/package.json (relative path: .)
        using description file: /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/package.json (relative path: ./src/shims/cheerio-query)
          no extension
            /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/cheerio-query doesn't exist
          .js
            /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/cheerio-query.js doesn't exist
          as directory
            /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/cheerio-query doesn't exist
[/Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/cheerio-query]
[/Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/cheerio-query.js]
 @ ./node_modules/@postlight/mercury-parser/dist/mercury.js 10:30-48
 @ ./src/index.js

ERROR in ./node_modules/@postlight/mercury-parser/dist/mercury.js
Module not found: Error: Can't resolve 'iconv-lite' in '/Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/dist'
resolve 'iconv-lite' in '/Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/dist'
  Parsed request is a module
  using description file: /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/package.json (relative path: ./dist)
    aliased from description file /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/package.json with mapping 'iconv-lite' to './src/shims/iconv-lite'
      using description file: /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/package.json (relative path: .)
        using description file: /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/package.json (relative path: ./src/shims/iconv-lite)
          no extension
            /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/iconv-lite doesn't exist
          .js
            /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/iconv-lite.js doesn't exist
          as directory
            /Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/iconv-lite doesn't exist
[/Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/iconv-lite]
[/Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/src/shims/iconv-lite.js]
 @ ./node_modules/@postlight/mercury-parser/dist/mercury.js 12:28-49
 @ ./src/index.js
```

from what i'm seeing here, it looks sort of like i might need to run some more project specific build steps? the `package.json` has some build scripts that i tried to run, like `rollup`, but then i got
```
ENOENT: no such file or directory, lstat '/Users/alexchoi/hnfd/js/node_modules/@postlight/mercury-parser/rollup.config.js'
```
which i see in the repo but is missing in the tgz yarn downloaded 
```
resolved "https://registry.yarnpkg.com/@postlight/mercury-parser/-/mercury-parser-2.0.0.tgz#1f5f123a6ed4df58731f96f2cf6dd97336f689e0"
```

anyhow, i'd love to just get the 
```
import Mercury from '@postlight/mercury-parser';

Mercury.parse(url).then(result => console.log(result));

```
example going - maybe you could help me out.

ultimately i am trying to get this built out into some javascript i can put into an ios app either
- in a jscontext to call from swift (executed in a corejs engine)
or
- shoved into a webview ( executed in a browser)

thanks!

## Steps to Reproduce

try to do this
```
yarn add @postlight/mercury-parser

```
```
import Mercury from '@postlight/mercury-parser';

Mercury.parse(url).then(result => console.log(result));

```

**Comment by benubois** [comment]
I think this import syntax isn’t supported in node. Try this: https://github.com/postlight/mercury-parser/issues/323#issuecomment-472350267

**Comment by heyalexchoi** [comment]
@benubois aren't i doing somewhat of the eqivalent? also, i am able to `import _ from 'lodash';`

**Comment by benubois** [comment]
¯\_(ツ)_/¯ I don’t really know either. Just sounded the same as the other issue. 

Did you try the alternate syntax?

**Comment by heyalexchoi** [comment]
i am able to run in node. these errors are from building with webpack.

**Comment by heyalexchoi** [comment]
no need to build with webpack, there are rollup build artifacts in `dist`.

for anyone interested in doing what i was trying to do:
i was not able to successfully run mercury parser in an ios javascriptcore jscontext. i think because of dependencies on document objects in `mercury.web.js`.

**Comment by thebenlamm** [comment]
I was able to build with webpack by doing the following:

1. In package.json remove all fields in `browser` besides for `main`. It should look like this:
```
"browser": {
    "main": "./dist/mercury.web.js"
  },
```
It seems webpack is getting confused by those fields. I'm not entirely sure why they are there to begin with.

2. In your webpack.config file add a `node` property in the root like this:
```
node: {
      net: 'empty',
      tls: 'empty',
      fs: 'empty'
    }
```
This is because those modules are built into node but are not in the browser.

HOWEVER after all this it will still not work because of cors.
`Access to fetch at 'https://medium.com/s/story/...' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

At this point I'm going to give in and do the parsing server side.
