### ISSUE TITLE
Error when trying to build react app with Mercury installed

### ISSUE THREAD

**Issue by tobecreated** [postlight/mercury-parser#341]
- **Platform**: Darwin Johns-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
- **Mercury Parser Version**: ^2.0.0
- **Node Version (if a Node bug)**:  v11.1.0
- **Browser Version (if a browser bug)**: N/A

## Expected Behavior

Build should succeed, with mercury-reader successfully accessing cheerio package.

## Current Behavior

Both npm run build and yarn build output the following error

Failed to compile.

./node_modules/@postlight/mercury-parser/dist/mercury.js
Cannot find module: 'cheerio'. Make sure this package is installed.

You can install this package by running: yarn add cheerio.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Steps to Reproduce

Open terminal, use the following:

1. npx create-react-app new-chrome-extension
2. cd new-chrome-extension
3. Adjust manifest.json to represent a chrome-extension
(e.g. 
{
  "manifest_version": 2,
  "name": "New Chrome Extension",
  "author": "ToBeCreated",
  "version": "1.0.1",
  "description": "Example manifest for recreating error.",
  "incognito": "split",
  "icons": {
    "16": "16.png",
    "48": "48.png",
    "128": "128.png"
  },
  "permissions": ["storage"]
}
3.1. OPTIONAL: Replace "build" in package JSON with "INLINE_RUNTIME_CHUNK=false react-scripts build"
4. Install mercury-reader with npm install @postlight/mercury-parser
5. npm install
6. npm run build
7. Error produced

## Detailed Description

Prevents use of mercury-parser inside react-based chrome extension

**Comment by adampash** [comment]
If I were to guess, there's something wrong with the build environment such that it's not respecting the `browser` section of `package.json`. A few node libraries are shimmed to make Mercury browser friendly — in the case of Cheerio, there's a modified version of jQuery. 

That's where I'd look to debug. I've installed/used Mercury using `create-react-app` without issues, so it seems possible that the extension is not respecting the browser-specific parts of the build.

**Comment by toufic-m** [comment]
This has been fixed in #302 and will be included in the next release/package version.

**Comment by toufic-m** [comment]
`v.2.1.0` (ca47f9c) has been released. Please update the `@postlight/mercury-parser` package to get the latest fixes.

https://github.com/postlight/mercury-parser/blob/master/CHANGELOG.md#210-apr-10-2019
