### ISSUE TITLE
Error: ETIMEDOUT

### ISSUE THREAD

**Issue by mursalal** [postlight/mercury-parser#344]
- **Platform**: Ubuntu 16.04 LTS
- **Mercury Parser Version**: 2.0.0
- **Node Version (if a Node bug)**: 10.15.3
- **Browser Version (if a browser bug)**:

## Current Behavior

Sometime returns this error:

{ Error: ETIMEDOUT
    at Timeout._onTimeout (/home/mitrandir/node_modules/request/request.js:760:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) code: 'ETIMEDOUT', connect: false }

## Steps to Reproduce

1. 2. 3. 4.

## Possible Solution

I think this is due to operations time.

**Comment by toufic-m** [comment]
Is this a persistent issue? In some cases it's simply a network timeout or connectivity issue, which is normal and sometimes unavoidable.

**Comment by mursalal** [comment]
@toufic-m I have good a network connection. This did not happen when I am trying parse one or two urls.

**Comment by toufic-m** [comment]
The web server for your request itself is a factor as well, not just your internet connection. If a web server is experiencing a huge amount of traffic or is having performance issues, there could be delays or timeouts in responses. So as long as it's a limited number of occurrences/isolated cases for this error, I'd say it's pretty normal.

**Comment by mursalal** [comment]
@toufic-m ok. Thanks!

**Comment by mursalal** [comment]
I understood what was the matter. I sent several URLs asynchronously. Because of this, requests did not have time for 10 seconds (timeout 10 seconds: https://github.com/postlight/mercury-parser/blob/b6c82f2b1679c86eb2d6b5eec8a50581a4bd99f8/src/resource/utils/constants.js#L12).
I am new in javascript. Can you explain me how to ran several promises one by one. For example: I have list of urls. I wanna parse them via Mercury one by one (synchronously).

**Comment by toufic-m** [comment]
@mursalal there are several ways to tackle this, the simplest one being the use of `await` as such:
```javascript
const result = await Mercury.parse(url);
```
You can read more about `await` [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await), and more about `async` functions (functions that can be "awaited") [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function).
