### ISSUE TITLE
Feature request: might Mercury reader work together with Vimium C?

### ISSUE THREAD

**Issue by gdh1995** [postlight/mercury-parser#356]
Some users of Vimium (an extension to use keyboard to control webpages and Chrome actions) has requested supports for the Mercury reader's page: https://github.com/philc/vimium/issues/3221, https://github.com/philc/vimium/issues/3285 . But, because Mercury reader creates iframes with a "src" of ”chrome-extension://...", Vimium can not work on your iframes in theory.

However I've made a customized Vimium (https://github.com/gdh1995/vimium-c) and it supports injection into other extensions, if only the target extension declares a CSP allowing Vimium C and adds `<script src="[Vimium C injector]">`  to HTML files.

Therefore, I wonder if your extension (Mercury reader) might add an option to allow users to enable the Vimium C's injection.

Besides, if not, could I publish a customized version of Mercury reader to support injection of Vimium C (I'll follow all the licenses) ?

Thanks a lot for this helpful project!

**Comment by mtashley** [comment]
Hi @gdh1995, thanks for your support of the project. Please feel free to publish a customized version which supports Vimium C.

**Comment by gdh1995** [comment]
@mtashley Sorry, but it seems that Mercury reader is not open-source, so could I modify the published extension package and re-publish it?
