### ISSUE TITLE
Parser outputs invalid JSON

### ISSUE THREAD

**Issue by Melsonzw** [postlight/mercury-parser#360]
- **Platform**: Windows 7
- **Mercury Parser Version**: 2.0.0
- **Node Version (if a Node bug)**: 10.15.3

## Expected Behavior

Output should be valid JSON, with all key-value pairs in double quotes.

## Current Behavior

Keys are not quoted, values are inside single quotes.

## Steps to Reproduce

The source code of the page is saved in **temp.html**
**parse.js** looks like this:
```javascript
var url = 'https://www.vn.nl/david-wallace-wells-de-onbewoonbare-aarde/';

const Mercury = require('@postlight/mercury-parser');
var fs = require('fs');

fs.readFile('temp.html', function (err, data) {
  if (err) throw err;
  Mercury.parse(url, {html: data}).then(result => console.log(result));
});
```

Run **node parse.js > out.json**
This file then contains the invalid JSON.

**Comment by adampash** [comment]
@Melsonzw The parser outputs a JavaScript object. If you'd like to convert the response to JSON, you could change your code like so:

```javascript
var url = 'https://www.vn.nl/david-wallace-wells-de-onbewoonbare-aarde/';

const Mercury = require('@postlight/mercury-parser');
var fs = require('fs');

fs.readFile('temp.html', function (err, data) {
  if (err) throw err;
  Mercury.parse(url, {html: data}).then(result => console.log(JSON.stringify(result)));
});
```
