### ISSUE TITLE
Can't resolve 'cheerio' in mercury-parser/dist'

### ISSUE THREAD

**Issue by Farbod29** [postlight/mercury-parser#363]
- **Platform**:
- **Mercury Parser Version**:
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**:

after importing import Mercury from '@postlight/mercury-parser'; in my react app I have 
Failed to compile.

./node_modules/@postlight/mercury-parser/dist/mercury.js
Module not found: Can't resolve 'cheerio' in '/Users/farbodaprin/Desktop/MASTER THISES/Master resources/SALMON/SALMON-PROGRAMING/Private Salmon/FeryAndSOmy/node_modules/@postlight/mercury-parser/dist'

## Expected Behavior

can use mercury as mentioned in readme.md

## Steps to Reproduce

1. 2. 3. 4.

**Comment by toufic-m** [comment]
This has been fixed in #302 and will be included in the next release/package version.

**Comment by toufic-m** [comment]
`v.2.1.0` (ca47f9c) has been released. Please update the `@postlight/mercury-parser` package to get the latest fixes.

https://github.com/postlight/mercury-parser/blob/master/CHANGELOG.md#210-apr-10-2019
