### ISSUE TITLE
TypeError: Cannot read property 'map' of null when parsing certain URLs

### ISSUE THREAD

**Issue by kulinsj** [postlight/mercury-parser#385]
- **Platform**: Mac OSX 10.13.6
- **Mercury Parser Version**: 2.1.0
- **Node Version (if a Node bug)**: 11.13.0

## Expected Behavior

Should be able to parse url

## Current Behavior

Encounter error when attempting to parse certain URLs.
`TypeError: Cannot read property 'map' of null`

## Steps to Reproduce

1. Call the `parse` method with the following URL (example) `https://www.nationalreview.com/corner/indias-economy-to-surpass-britains/`

## Detailed Description

The error is hit here:
```
Trace: TypeError: Cannot read property 'map' of null
    at Object.<anonymous> (.../node_modules/@postlight/mercury-parser/dist/mercury.js:1267:43)
```
It occurs because the "urlSet" variable ends up being a string with length 1 which is only whitespace: a single space character. The urlSet.match function subsequently returns `null` and an error is hit when calling .map() on that `null`

## Possible Solution

One solution that worked was adding an extra condition to the `if` statement on 1262
```
if (urlSet) {
// changed to:
if (urlSet && urlSet.trim()) {
```
But a more general purpose solution is to properly account for the possible `null` returned from the match function
```
if (urlSet) {
  // a comma should be considered part of the candidate URL unless preceded by a descriptor
  // descriptors can only contain positive numbers followed immediately by either 'w' or 'x'
  // space characters inside the URL should be encoded (%20 or +)
  var candidates = urlSet.match(/(?:\s*)(\S+(?:\s*[\d.]+[wx])?)(?:\s*,\s*)?/g);
  if (!candidates) return; // <----- Adding this line here
  var absoluteCandidates = candidates.map(function (candidate) {
    // a candidate URL cannot start or end with a comma
    // descriptors are separated from the URLs by unescaped whitespace
    var parts = candidate.trim().replace(/,$/, '').split(/\s+/);
    parts[0] = URL.resolve(rootUrl, parts[0]);
    return parts.join(' ');
  });

  var absoluteUrlSet = _toConsumableArray(new _Set(absoluteCandidates)).join(', ');

  setAttr(node, 'srcset', absoluteUrlSet);
}
```

**Comment by toufic-m** [comment]
Thanks for reporting and looking into this, #386 addresses this issue.
