### ISSUE TITLE
dailymail.co.uk is missing most of its content after parsing

### ISSUE THREAD

**Issue by jmbox80** [postlight/mercury-parser#389]
- **Platform**: Windows 10, 64-bit
- **Mercury Parser Version**: unknown
- **Node Version (if a Node bug)**: n/a
- **Browser Version (if a browser bug)**:  Version 73.0.3683.103 (Official Build) (64-bit)

## Expected Behavior

All article content should be parsed and displayed.

## Current Behavior

No meaningful article content is rendered after the author's name, date, etc.

## Steps to Reproduce

Visit this page:  https://www.dailymail.co.uk/sciencetech/article-6935471/The-type-molecule-formed-universe-Big-Bang-found.html

## Detailed Description
Source page screenshot:
![image](https://user-images.githubusercontent.com/34203068/56372350-ceaa4a00-61cc-11e9-8c1b-7350af71c684.png)

Rendered page screenshot:
![image](https://user-images.githubusercontent.com/34203068/56372410-ebdf1880-61cc-11e9-8e6c-c14a428a9a48.png)

**Comment by mtashley** [comment]
Hi @jmbox80, I recommend creating a custom parser for this specific website. Please see: https://github.com/postlight/mercury-parser/blob/master/src/extractors/custom/README.md
