### ISSUE TITLE
meta "content  attr" transform to "value attr"

### ISSUE THREAD

**Issue by Enivel** [postlight/mercury-parser#393]
https://ol.3dmgame.com/news/201904/18573.html

<meta name="Description" content="更新：之前人民日报发布的Uzi专访视频现在已经被删除，人民日报的官方也已经删除了之前发布的微博，具体原因现在尚不知晓，希望未来还可以重新看到这篇报道吧。今天（4月12日）" />
 

![image](https://user-images.githubusercontent.com/1982819/56561060-b1b0b500-65d8-11e9-9644-c9d4ca313023.png)

**Comment by Enivel** [comment]
original html 



meta name="Description" content="更新：之前人民日报发布的Uzi专访视频现在已经被删除，人民日报的官方也已经删除了之前发布的微博，具体原因现在尚不知晓，希望未来还可以重新看到这篇报道吧。今天（4月12日）"

**Comment by toufic-m** [comment]
Could you please share some more details describing the actual issue and what you're trying to do?

I tested creating a custom parser with that link, and using the value of the `Description` `meta` as a `dek` and received the following:

```json
"dek": "更新：之前人民日报发布的Uzi专访视频现在已经被删除，人民日报的官方也已经删除了之前发布的微博，具体原因现在尚不 知晓，希望未来还可以重新看到这篇报道吧。今天（4月12日）",
```

even when the value is encoded in the generated HTML fixture:

```html
	<meta name="Description" value="&#x66F4;&#x65B0;&#xFF1A;&#x4E4B;&#x524D;&#x4EBA;&#x6C11;&#x65E5;&#x62A5;&#x53D1;&#x5E03;&#x7684;Uzi&#x4E13;&#x8BBF;&#x89C6;&#x9891;&#x73B0;&#x5728;&#x5DF2;&#x7ECF;&#x88AB;&#x5220;&#x9664;&#xFF0C;&#x4EBA;&#x6C11;&#x65E5;&#x62A5;&#x7684;&#x5B98;&#x65B9;&#x4E5F;&#x5DF2;&#x7ECF;&#x5220;&#x9664;&#x4E86;&#x4E4B;&#x524D;&#x53D1;&#x5E03;&#x7684;&#x5FAE;&#x535A;&#xFF0C;&#x5177;&#x4F53;&#x539F;&#x56E0;&#x73B0;&#x5728;&#x5C1A;&#x4E0D;&#x77E5;&#x6653;&#xFF0C;&#x5E0C;&#x671B;&#x672A;&#x6765;&#x8FD8;&#x53EF;&#x4EE5;&#x91CD;&#x65B0;&#x770B;&#x5230;&#x8FD9;&#x7BC7;&#x62A5;&#x9053;&#x5427;&#x3002;&#x4ECA;&#x5929;&#xFF08;4&#x6708;12&#x65E5;&#xFF09;">
```

**Comment by Enivel** [comment]
Sorry  my bed.  In browser webpage this content  in the  "content attributes" ,but in generated HTML It has become "value attributes",  i think is web policy.

**Comment by toufic-m** [comment]
Mercury normalizes all `meta` tags (by converting the `content` attribute into `value`, and the `property` attribute into `name`) so that they can all be queried similarly:

https://github.com/postlight/mercury-parser/blob/master/src/resource/utils/dom/normalize-meta-tags.js#L21
