### ISSUE TITLE
Why not support the ".first()" method

### ISSUE THREAD

**Issue by Enivel** [postlight/mercury-parser#394]
Hi When I want to get an image from the body of the article as lead_image, how do I implement it?

**Comment by toufic-m** [comment]
You could use the `:first-of-type` CSS pseudo-class in your selector to match the first image in the article body.

**Comment by Enivel** [comment]
hello  in this case  i used anything i can, only .first() solve it
https://ol.3dmgame.com/news/201904/18573.html
