### ISSUE TITLE
Feature proposal - Allow to add custom extractor by API

### ISSUE THREAD

**Issue by patou** [postlight/mercury-parser#397]
- **Platform**: All
- **Mercury Parser Version**: All
- **Node Version (if a Node bug)**: All
- **Browser Version (if a browser bug)**: All

## Expected Behavior

Allow to add custom extractor by API, for example : 
```
import Mercury from '@postlight/mercury-parser';
import ExampleExtractor from './ExampleExtractor';

Mercury.add("example.com", ExampleExtractor);
Mercury.parse("www.example.com").then(result => console.log(result));
```

## Current Behavior

Actually, we must add custom extractor in the source code of Mercury Parser.
It's can be a good option to allow api users to add is own private extractor.

**Comment by mtashley** [comment]
This feature has been added as part of https://github.com/postlight/mercury-parser/pull/484
