### ISSUE TITLE
maths rendering on wordpress

### ISSUE THREAD

**Issue by isomorphisms** [postlight/mercury-parser#399]
https://terrytao.wordpress.com/2008/03/24/dvirs-proof-of-the-finite-field-kakeya-conjecture/

Mercury does a bad render of the first page of the above.

Wordpress has a `$latex 360 \deg$` style syntax for maths rendering, which mercury probably misses.

It’s not super common, but may be an easy feature to add, on a major platform.

**Comment by isomorphisms** [comment]
https://nlp.stanford.edu/IR-book/html/htmledition/latent-semantic-indexing-1.html

Similar problem here.

**Comment by mtashley** [comment]
Closing, as this issue appears to relate to the mercury reader. 

*mercury-parser*
![Screen Shot 2019-08-20 at 10 04 51 AM](https://user-images.githubusercontent.com/26754075/63368059-f9024480-c331-11e9-96f1-8bc1c4097ed1.png)
