### ISSUE TITLE
ETIMEDOUT error

### ISSUE THREAD

**Issue by NightMachinary** [postlight/mercury-parser#413]
**Platform: macOS Mojave**
Mercury Parser Version: @postlight/mercury-parser@2.1.0
**Node Version v11.6.0** 

```
mercury-parser 'https://stratechery.com/2019/disney-and-the-future-of-tv/'

Mercury Parser encountered a problem trying to parse that resource.

{ Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/@postlight/mercury-parser/node_modules/postman-request/request.js:1057:19)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5) code: 'ETIMEDOUT', connect: true }
```

I can't reproduce this problem on my VPS, but it happens every single time on my laptop.

**Comment by NightMachinary** [comment]
I just upgraded to node-12.1.0, and the issue remains. And it works for other urls, e.g., https://en.wikipedia.org/wiki/Apple_Inc. .

**Comment by toufic-m** [comment]
Mercury Parser has a fetch timout of 10000 milliseconds
https://github.com/postlight/mercury-parser/blob/a38c727a0aee058f640f03cd25f0930adda45a4c/src/resource/utils/constants.js#L12

https://github.com/postlight/mercury-parser/blob/a38c727a0aee058f640f03cd25f0930adda45a4c/src/resource/utils/fetch-resource.js#L94

What's likely happening is that the fetch request is taking more than 10 seconds on your laptop, but less time on your VPS, which is mainly connection-related.

**Comment by NightMachinary** [comment]
As my laptop connection is not slow (around 16 mbps), and I actually
connect to a VPN server on that same VPS, either this is a more serious
bug, or this timeout needs to be either set higher or be a command-line
option. (Turning it into an option also makees it clear if it is indeed
just a timeout or sth is wrong.)

**Comment by toufic-m** [comment]
Is your laptop connected to the same VPN as that on the VPS? If not, could you please test that out?
Also, could you please test manually increasing the `10000`ms `FETCH_TIMEOUT `?

**Comment by NightMachinary** [comment]
My laptop uses that VPS as a VPN, the VPS connects directly to the internet.
I will test that out but I don’t know node’s toolchain, so it might get a
while till I get to it ...

**Comment by mtashley** [comment]
Just tested original url and all appears to be working. Please feel free to reopen an issue and reference this ticket if you are still experiencing the timeout error on the latest version. As part of a general cleanup, I'm going to go ahead and close this one.
