### ISSUE TITLE
Mercury icon: Support for browser's dark themes

### ISSUE THREAD

**Issue by verlok** [postlight/mercury-parser#417]
- **Platform**: Windows 10
- **Browser Version (if a browser bug)**: Opera 58.0.3135.132

## Expected Behavior

On dark themes, the icon should be visible

## Current Behavior

On dark themes, the icon is not visible

## Steps to Reproduce

1. Enable dark theme in Opera
2. Look at the icon

It's like this:

![image](https://user-images.githubusercontent.com/1127721/57513635-03627a80-730f-11e9-98d5-a933fe940fe5.png)

At mouse over:

![image](https://user-images.githubusercontent.com/1127721/57513673-14ab8700-730f-11e9-836d-3a266bcd5583.png)

## Possible Solution

If there's a way to detect a dark theme, provide a white icon instead.

If there isn't, just provide a transparent black icon so if the background is white we'll see gray, if the background is gray.

Alternative solution: add a ligher stroke around the icon, so that it's visible on dark backgrounds.

**Comment by verlok** [comment]
I've just updated to Opera 60.0.3255.83.
The problem is solved there!

![image](https://user-images.githubusercontent.com/1127721/57531717-5b62a680-733a-11e9-9b0a-551edf09714a.png)

Super fast issue fix! Hahahaha

**Comment by teamtamer** [comment]
I have this issue with  Google Chrome Version 77.0.3865.90 (Official Build) (64-bit).
When using 'Designer Theme'.  (theme link below)

Image attached - similar to original reported Opera problem.

Icon is (functionally) invisible when toolbar is dark. 


Links:
Designer Theme: https://chrome.google.com/webstore/detail/designer-theme/lofnfjohfooeliifjdjjhckbhdcjempk

![Annotation 2019-09-25 122500](https://user-images.githubusercontent.com/6753746/65564363-01344c00-df90-11e9-89fe-6b4a5e4968ba.png)
![Annotation 2019-09-25 122717](https://user-images.githubusercontent.com/6753746/65564372-042f3c80-df90-11e9-836d-d05d03384b0a.png)
