### ISSUE TITLE
Support for scientific articles seems lacking

### ISSUE THREAD

**Issue by farleylai** [postlight/mercury-parser#418]
- **Platform**: Chrome on Ubuntu 16.04
- **Mercury Parser Version**: 4.2.4.0
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**: 69.0.3497.100 (Official Build) (64-bit)

## Expected Behavior

1. Should select text as usual after applying Mercury reader
2. Should retain Math symbol rendering
3. Should format code along with text appropriately

## Current Behavior

1. The selection is always from the bottom most to the current cursor position
2. Math symbols become plain text and unreadable
3. Nearly a mess with a bunch of iframes/boxes without text wrap

## Steps to Reproduce

1a. Expected selection

![select-expected](https://user-images.githubusercontent.com/158540/57630216-34d78200-756b-11e9-9fe0-71152fc6e218.png)

1b. Mercury selection

![select-mercury](https://user-images.githubusercontent.com/158540/57630225-399c3600-756b-11e9-83d5-50803295e244.png)

2.3.a. Math/code expected

![code-expected](https://user-images.githubusercontent.com/158540/57630560-d363e300-756b-11e9-9df7-be55c8d778d1.png)

2.3.b. Math/code rendered

![code-mercury](https://user-images.githubusercontent.com/158540/57630579-dbbc1e00-756b-11e9-8ee0-bcac4bd6ca9b.png)

## Detailed Description

I would like a BETTER reading experience of scientific articles.
At least good enough to print as PDF.

Scientific articles like [this](http://nlp.seas.harvard.edu/2018/04/03/attention.html#) should be part of your production testing.

## Possible Solution

1. the text selection is likely a bug
2. math/code rendering requires further parsing

**Comment by mtashley** [comment]
Hi @farleylai,

I recommend [creating a custom extractor](https://github.com/postlight/mercury-parser/tree/master/src/extractors/custom) for the specific website(s) you are targeting.
