### ISSUE TITLE
TheAtlantic incorrect parsing

### ISSUE THREAD

**Issue by pozh** [postlight/mercury-parser#432]
- **Platform**: Win10 64bit
- **Mercury Parser Version**: 2.1.0
- **Node Version (if a Node bug)**: 8.12
- **Browser Version (if a browser bug)**: 

## Expected Behavior

should take the article text

## Current Behavior

took just a part of the article, 

## Steps to Reproduce

link: https://www.theatlantic.com/technology/archive/2019/04/influencers-are-abandoning-instagram-look/587803/

## Possible Solution

I think it's impossible to make the extractor work for every single website, and I like the way Calibre handles that problem - I'm talking about the "recipes". Maybe there's a way to implement a similar system inside your parser?

**Comment by equivalentideas** [comment]
@pozh you might like to contribute a custom parser for this site https://github.com/postlight/mercury-parser/blob/master/src/extractors/custom/README.md

**Comment by mtashley** [comment]
Fix merged in https://github.com/postlight/mercury-parser/pull/475
