### ISSUE TITLE
normalizeSpaces strips highlight.js formatting

### ISSUE THREAD

**Issue by theolampert** [postlight/mercury-parser#437]
- **Platform**: Any
- **Mercury Parser Version**: 2.1.0
- **Node Version (if a Node bug)**: N/A
- **Browser Version (if a browser bug)**: N/A

## Expected Behavior

Code snippets should retain formatting

## Current Behavior

Code snippets such as those created with highlight js often contain nested `span` tags. The function `normalizeSpaces` is stripping formatting information from these as it's not currently checking for nested values in `pre` or `code` tags.

## Steps to Reproduce

1. Attempt to scrape an html document containing highlightjs code
2. Verify result does not retain formatting

## Possible Solution

I'm not entirely sure how you'd like to proceed but I have time in the next few days to submit a PR if you let me know you'd like this addressed. Otherwise I will maintain a fork for myself.

**Comment by theolampert** [comment]
Looks like this was addressed in https://github.com/postlight/mercury-parser/commit/a250f403f5? I'm going to close my issue since it's working for me now.

**Comment by exentrich** [comment]
I think this issue should be re-opened because `<span>` elements in `<pre>` tags still removed.
Here example page: https://medium.com/@calvin.hsieh/steps-to-install-mongodb-on-aws-ec2-instance-62db66981218
If you enable Mercury Parser you will not see any code examples on this page
