### ISSUE TITLE
Does Mercury support content without inline images?

### ISSUE THREAD

**Issue by nitinthewiz** [postlight/mercury-parser#438]
I understand that Mercury parser does a pretty good job of extracting both lead_image_url and keeping inline images in the content.

However, if I want to remove all inline images from the content and keep only the text, is that possible? I didn't see any such option in the parse function.

Is the best way to do this to use a custom extractor that ignores images? Or a more system-wide option like contentType is the right approach (perhaps called keepInlineImages, set to True by default)?

**Comment by mtashley** [comment]
Hi @nitinthewiz,

Your best bet here is create a custom extractor and remove the specific elements as needed. See [Cleaning content from an article](https://github.com/postlight/mercury-parser/tree/master/src/extractors/custom#cleaning-content-from-an-article) for additional info.

A second strategy you could use is by modifying the *clean-images.js*, which removes very small images by default.

```js
function cleanForHeight($img, $) {
  const height = parseInt($img.attr('height'), 10);
  const width = parseInt($img.attr('width'), 10) || 20;

  // Remove images that explicitly have very small heights or
  // widths, because they are most likely shims or icons,
  // which aren't very useful for reading.
  if ((height || 20) < 10 || width < 10) {
    $img.remove();
  } else if (height) {
    // Don't ever specify a height on images, so that we can
    // scale with respect to width without screwing up the
    // aspect ratio.
    $img.removeAttr('height');
  }

  return $;
}
```
