### ISSUE TITLE
GenericWordCountExtractor fails with anything other than a div element

### ISSUE THREAD

**Issue by theolampert** [postlight/mercury-parser#442]
- **Platform**: Any
- **Mercury Parser Version**: 2.10
- **Node Version (if a Node bug)**: 12.0.1

## Expected Behavior

When given an html string wrapped in `section / div / article / main` ect the `GenericWordCountExtractor` should return the correct wordcount. 

## Current Behavior

`GenericWordCountExtractor` will return a wordcount of 1 if the wrapper element is not of type `div`

## Steps to Reproduce

The easiest way to reproduce this is to edit the unit test cases here https://github.com/postlight/mercury-parser/blob/15f7fa1e27fe6b47c87da40ba4fce9b2db7934ec/src/extractors/generic/word-count/extractor.test.js

Add examples that use different tags.

## Possible Solution
Doing something like the following in [here](https://github.com/postlight/mercury-parser/blob/15f7fa1e27fe6b47c87da40ba4fce9b2db7934ec/src/extractors/generic/word-count/extractor.js#L8) 

```js
const $content = $('div, section, article, main').first();
```
I can open a PR for this if desired.

**Comment by adampash** [comment]
@theolampert I believe the reason for this was that, in theory, all the final output should be wrapped in a `div`, which means there may be something unexpected happening there. Can you provide an example url where that's not the case?

**Comment by theolampert** [comment]
@adampash ah that makes a lot more sense now. I experienced this a number of times, I'll try and dig up an example. I'm running puppeteer and parsing the resulting html to mercury parser which might have something todo with it.

**Comment by adampash** [comment]
@theolampert thanks!
