### ISSUE TITLE
elpais.com Incorrect parsing

### ISSUE THREAD

**Issue by nmrsousa** [postlight/mercury-parser#451]
- **Platform**: Windows 10
- **Mercury Parser Version**: 4.2.4.0
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**: Chrome Version 72.0.3626.109 (Official Build) (32-bit)

## Expected Behavior
Parsed page should have whole information

## Current Behavior
Only the information on grey box at the bottom was displayed

## Steps to Reproduce
Open page https://elpais.com/politica/2019/07/03/actualidad/1562148329_246724.html

## Possible Solution
Parse webpage correctly, with all information, both on the main text and the text on the box.

**Comment by mtashley** [comment]
Hi @nmrsousa, I recommend creating a custom parser for this use-case.

Please see: https://github.com/postlight/mercury-parser/blob/master/src/extractors/custom/README.md
