### ISSUE TITLE
CORS issue in Chrome

### ISSUE THREAD

**Issue by hannadomagala** [postlight/mercury-parser#452]
- **Platform**: Windows 64-bit
- **Mercury Parser Version**: ^2.1.1
- **Node Version (if a Node bug)**: 10.16.0
- **Browser Version (if a browser bug)**: Chrome 75.0.3770.100 (64-bit)

## Expected Behavior

Mercury should parse url in the browser.

## Current Behavior

Having trouble with CORS when parsing in the browser:

`Access to XMLHttpRequest at 'https://trackchanges.postlight.com/building-awesome-cms-f034344d8ed' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

## Steps to Reproduce

I'm building next.js app with React front & Express backend.
For now used your example code from docs.
Request works in the server but I need it to be done in the browser, then I get this CORS issue.

## Detailed Description

Am I doing something wrong? Would love to get some tip how to get this right ASAP.

```
getArticleInfo = async url => {
    const info = await Mercury.parse(url);
    this.setState({ articleInfo: info });
  };
```

Also tried to set Allow-Control-Allow-Origin:* to configuration object to headers, then got this:
`Access to XMLHttpRequest at 'https://trackchanges.postlight.com/building-awesome-cms-f034344d8ed' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

**Comment by gatlanticus** [comment]
@hannadomagala **CORS** is an [inbuilt defense mechanism](https://stackoverflow.com/questions/31581051/browser-based-client-side-scraping)  in web browsers to prevent the situation where a user visits site A, but then that site secretly (and nefariously) downloads something from site B. So this is not an issue with mercury-parser but the basic design of browsers, and "fixing" this involves comprising user security. The proper solution is therefore to stick to the server side, which you said is working for you.

**Comment by hannadomagala** [comment]
@gatlanticus I did so! Thanks for response.
