### ISSUE TITLE
AFR.com incorrect parsing

### ISSUE THREAD

**Issue by equivalentideas** [postlight/mercury-parser#457]
- **Platform**: Linux, via https://github.com/feedbin/extract
- **Mercury Parser Version**: 2.1.1

## Expected Behavior

Should get the full article text of post https://www.afr.com/news/politics/national/tell-em-they-re-dreamin-on-energy-20190520-p51pcv

## Current Behavior

Only gets half the article content, starting from the last `<section>` within the `<main>` which they use to wrap their main post. This means the `content` is incomplete.

## Steps to Reproduce

Parse https://www.afr.com/news/politics/national/tell-em-they-re-dreamin-on-energy-20190520-p51pcv and compare the content extracted to the page text.

## Detailed Description

I'm using the parser to collect records of fossil fuel company lobbying activities, and need the full post text for this analysis.

Having incomplete text means I need to manually review the statements that are missing.

## Possible Solution

Possible solution might be to contribute a [custom site extractor](https://github.com/postlight/mercury-parser/blob/master/src/extractors/custom/README.md) for this site.

I'm happy to have a crack at that and contribute a PR.

Best wishes,

Luke

**Comment by mtashley** [comment]
Hi @equivalentideas, I recommend creating a custom parser. Please see: https://github.com/postlight/mercury-parser/blob/master/src/extractors/custom/README.md
