### ISSUE TITLE
Support for Python and/or other languages?

### ISSUE THREAD

**Issue by BlackLight** [postlight/mercury-parser#459]
I have been a proud user of the Mercury Reader web API for a long time, and I've been a bit disappointed when I've recently seen some of my software breaking because of the deprecation of that API (although I can imagine the reasons behind).

My main project that used the API is written in Python, and even though I could either use the `mercury-parser` library in a Node.js project or spawn a `mercury-parser-api` service, I'd like to keep all the things together in my project and use (if possible) a native Python way to achieve my purpose.

Would it be possible to provide a binding for the parser API in Python, or even a tiny wrapper in Python around either the service or the JavaScript library (with the potential for it to be extended in other languages)?

**Comment by mtashley** [comment]
Hi @BlackLight ,

Currently there are no immediate plans to create a Python version, but it may be considered in the future.
