### ISSUE TITLE
google extension is fetching data from an url while command line is getting returned with an  empty body

### ISSUE THREAD

**Issue by prshntchourasia** [postlight/mercury-parser#474]
While fetching the content from https://www.thinkhdi.com command line is returning with an empty body as shown in the figure-1 
![mercury-parser-command-line](https://user-images.githubusercontent.com/14184935/63250786-08c64e00-c28a-11e9-865f-4ee8bf055557.png)

but in the mercury parser reader (chrome extension) it is working absolutely fine
![mercury-parser-chrome-extension](https://user-images.githubusercontent.com/14184935/63250790-0e239880-c28a-11e9-90c1-6d4f218e4260.png)

**Comment by mtashley** [comment]
Hi @prshntchourasia, it's likely they are running different versions of the parser. Please feel free to submit a custom parser for the  thinkhdi.com website as well.

**Comment by grigoriy-didorenko** [comment]
Hi @mtashley 
According to the description, "Mercury Parser powers the Mercury AMP Converter and Mercury Reader", however, I faced a few cases when Mercury Parser is behind Mercury Reader. I can't get the point, if Mercury Reader is built on the top of Mercury Parser, they should bring the at least same results or Mercury Parser could be even better in case when some changes are made but they are not in the release version yet.

Could you please clarify the situation with parsers version?
