### ISSUE TITLE
mercury reader chrome extension not working

### ISSUE THREAD

**Issue by SB2020-eye** [postlight/mercury-parser#619]
Hi. I used Mercury Reader as a Chrome extension in the past. (Really great!) I removed it for a while b/c I wasn't reading as much at the time. I could really utilize it again. I reinstalled (turned it on in Chrome Extensions.) But the rocket icon is always gray, not orange. Right clicking the gray icon and selecting "Mercury Reader" or "Open in Mercury Reader" doesn't work either.

Any suggestions? I did try to find a solution or just remedy for my own ignorance; but without success.

**Comment by johnholdun** [comment]
Hello there! I couldn't recreate this issue and haven't heard any other reports of it. If you're still having trouble, please feel free to comment again on this issue or start a new one, and we can work together on diagnosing it. Thank you!
