### ISSUE TITLE
AMP converter issue

### ISSUE THREAD

**Issue by Marshsyl** [postlight/mercury-parser#623]
# ##Mismatched domains
  Canonical version
http://marshsyl.com/
AMP version
https:/z/mercury.postlight.com/amp?url=http://www.marshsyl.com/

- **Platform**:
- **Mercury Parser Version**:
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**:

## Steps to Reproduce

1. 2. 3. 4.

**Comment by johnholdun** [comment]
Hi there! Unfortunately, the Mercury AMP Converter has been discontinued, so the AMP version of your URL will no longer work. Sorry for the inconvenience.
