### ISSUE TITLE
This issues page is pretty ridiculous

### ISSUE THREAD

**Issue by LongHawl** [postlight/mercury-parser#641]
First, I added an issue five days ago and so far as I can tell nobody has even read the question.
I think I know why and that leads to this "issue" post.
Have you looked at the instructions for reporting an issue? Would even one person in a thousand understand what was being requested as feedback?   For example, read the issue "template" instructions below.......

Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
Mercury-Parser Version: the specified version in your `package.json` file
Node Version: output of `node --version` 

Seriously? If I understand any of that I would probably be technically competent enough to write my own version of Reader.
And that is just the tip of the iceberg of technical jargon that is being requested when you report an issue. 
......... Give me a break! ..........

Here is what I would like to do. I have run across a webpage that I would like to "Readerize" if you will, and send to Kindle for later reference. This particular webpage is 100% unaffected by Mercury Reader. Absolutely NOTHING changes on the page when I use the Reader extension. I mean NOTHING! I would think postlight would be interested in examining the page and determine why their' program fails utterly in that instance. How else are you supposed to make your product viable if you don't allow any means for users to easily and clearly report instances where it fails? 

Really..... this "issues: form is just insane. 
The end!

Thanks for reporting an issue!

This issue tracker is for bugs and issues found within Mercury Parser.

Please fill in as much of the template below as you're able.

Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
Mercury-Parser Version: the specified version in your `package.json` file
Node Version: output of `node --version`

If possible, please provide a stack trace and/or code that demonstrates the
problem, keeping it as simple and free of external dependencies as you are able.
-->

- **Platform**:
- **Mercury Parser Version**:
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**:

## Steps to Reproduce

1. 2. 3. 4.

**Comment by johnholdun** [comment]
Thanks for your feedback. Please feel free to open a new issue with details on the page you've encountered that is not being affected by Reader.

You're welcome to leave some or all of the issues template blank if the information it requests is not accessible to you or relevant to your issue. We provide that template as a convenience for submitters and maintainers alike, to ensure that we're collecting as much context as possible to aid in resolving issues efficiently.
