### ISSUE TITLE
Question Is this project dead ?

### ISSUE THREAD

**Issue by alanalvarado** [postlight/mercury-parser#653]
Is this project dead ?

Thanks!

**Comment by cesarvarela** [comment]
I'm wondering the same

**Comment by alanalvarado** [comment]
turndown needs to be updated and be able to select extra turndown options, I also would like to add two enhancements, machine learning for code language detection for pre elements, So I can clip tutorial webpage beautifully formatted, and also I need some other YAML metadata

**Comment by chuanqisun** [comment]
Wondering the same. Are there alternative libraries out there with active development?

**Comment by ba32107** [comment]
+1

**Comment by phms** [comment]
I'm moving my project to this API: https://rapidapi.com/fivefilters/api/full-text-rss/
More in: https://txtify.it/ and http://ftr.fivefilters.org/

**Comment by ba32107** [comment]
@phms this is an API though right? I need a library

**Comment by chuanqisun** [comment]
Maybe https://github.com/mozilla/readability?

**Comment by ba32107** [comment]
Yep I found that, haven't tried it yet though. There is also https://github.com/flickz/newspaperjs (haven't tried it either)

**Comment by johnholdun** [comment]
Hello! Maintenance has been slow but this project is not dead. Please feel free to open new issues or PRs with any updates you'd like to see to Mercury. Thank you!
