### ISSUE TITLE
AMP generator is not working mercury.postlight.com

### ISSUE THREAD

**Issue by amit-exp** [postlight/mercury-parser#680]
I have added this tag on my site but it is not working. Getting 500 error on Google Search Console.
`<link rel="amphtml" href="https://mercury.postlight.com/amp?url=http://winningwriters.com/our-contests/north-street-book-prize">`
If I run this particular URL on browser, it shows 500 Error message.
https://mercury.postlight.com/amp?url=http://winningwriters.com/our-contests/north-street-book-prize
Please help. 
Thank you!

**Comment by johnholdun** [comment]
Hello! I'm sorry, but the Mercury AMP Converter has been discontinued. We're working on a more instructive result here than a 500 error, as well as removing the information about the converter from the site.
